#include <iostream>

/**
 Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

 By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/
int main()
{
    std::uint32_t j=1, k=2, sum=0, result=0;
    while (j<4000000) {
        sum = j+k;
        j = k;
        k = sum;
        if (j%2 == 0) {
            result += j;
        }
    }

    std::cout << result << std::endl;
    return 0;
}
